sudo: required

services: docker

before_install: 
  - docker login -u hawkdaily -p 867b8575-5a34-4a07-b120-623902898692
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test